package main

import (
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"strings"
)

func setupPermissions() {
	// Check if running as root
	if os.Getuid() != 0 {
		fmt.Println("❌ Run this command with sudo:")
		fmt.Println("   sudo nodestral-agent setup-permissions")
		os.Exit(1)
	}

	// Detect agent service user
	agentUser := detectAgentUser()
	if agentUser == "" {
		// Agent runs as root — no sudoers needed
		fmt.Println("✅ Agent runs as root. No permission setup needed.")
		return
	}

	// Check if sudoers file already exists
	sudoersPath := "/etc/sudoers.d/nodestral-agent"
	if _, err := os.Stat(sudoersPath); err == nil {
		fmt.Println("✅ Permissions already configured.")
		return
	}

	// Generate sudoers content
	content := generateSudoers(agentUser)

	// Validate with visudo
	if err := validateSudoers(content); err != nil {
		fmt.Printf("❌ Sudoers validation failed: %v\n", err)
		os.Exit(1)
	}

	// Write file
	if err := os.WriteFile(sudoersPath, []byte(content), 0440); err != nil {
		fmt.Printf("❌ Failed to write sudoers file: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("✅ One-click restart enabled.")
	fmt.Println("   You can now restart services from the Nodestral dashboard.")
}

func detectAgentUser() string {
	// Try to read from systemd unit
	cmd := exec.Command("systemctl", "show", "nodestral-agent", "-p", "User")
	output, err := cmd.Output()
	if err == nil {
		u := strings.TrimSpace(strings.TrimPrefix(string(output), "User="))
		if u != "" && u != "root" {
			return u
		}
	}

	// Try to read from config file
	for _, path := range []string{"/etc/nodestral/agent.yaml", "/etc/nodestral/agent.yml", "/opt/nodestral/agent/config.yaml"} {
		data, err := os.ReadFile(path)
		if err == nil {
			for _, line := range strings.Split(string(data), "\n") {
				if strings.HasPrefix(line, "user:") {
					return strings.TrimSpace(strings.TrimPrefix(line, "user:"))
				}
			}
		}
	}

	// Check current user
	u, err := user.Current()
	if err == nil && u.Username != "root" {
		return u.Username
	}

	return ""
}

func generateSudoers(agentUser string) string {
	return fmt.Sprintf(`# Nodestral agent — service management permissions
# Generated by: sudo nodestral-agent setup-permissions
# Do not edit manually.

%s ALL=(root) NOPASSWD: /usr/bin/systemctl start *
%s ALL=(root) NOPASSWD: /usr/bin/systemctl stop *
%s ALL=(root) NOPASSWD: /usr/bin/systemctl restart *
%s ALL=(root) NOPASSWD: /usr/bin/systemctl status *
`, agentUser, agentUser, agentUser, agentUser)
}

func validateSudoers(content string) error {
	cmd := exec.Command("visudo", "-cf", "-")
	cmd.Stdin = strings.NewReader(content)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("visudo validation failed: %s", string(output))
	}
	return nil
}
